### ISSUE TITLE
Build GitHub Action for Staging deployment

### ISSUE THREAD

**Issue by cbaudouinjr** [codeRIT/brickhack.io#1010]
Part of TravisCI -> GitHub Actions migration

**Comment by peterkos** [comment]
Should be fixed in #1015 ; however, I think we can try using another (private) repo, and set the action to [deploy externally](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository). 
This way we won't have to deal with the slow I/O on current staging and we can leverage GH pages again!
