### ISSUE TITLE
Attempting to delete admin causes site to freeze

### ISSUE THREAD

**Issue by chrisbaudouinjr** [codeRIT/brickhack.io#680]
When attempting to delete an admin via the Admins section, the site will freeze whenever the delete button is clicked.

**REPRO**
Navigate to brickhack.io
Sign into an admin account with full access
Navigate to 'Admins'
Click on an admin and click 'Delete'
Site will freeze

**CONFIGURATION**
Safari Version 12.0.1 (14606.2.104.1.1)
macOS 10.14.1

**Comment by sman591** [comment]
I'm _pretty sure_ I found the bug causing this --- it was causing super flakey test results on hackathon_manager's test suite, which would time out after 10 minutes 80% of the time... something with validating unique user emails.

Should be fixed with the most recent upgrade to hackathon manager, but let me know if you see it again.
